import type { ProjectQuestionOption } from "@/types/bid";

/** Synthetic option id for “Other (describe)” — not generated by AI. */
export const MCQ_OTHER_OPTION_ID = "__other__";

export function optionsWithOther(
  opts: ProjectQuestionOption[],
  /** Shown on the synthetic “Other” row (e.g. last “anything else” question). */
  otherLabel = "Other — describe below",
): ProjectQuestionOption[] {
  if (opts.some((o) => o.option_id === MCQ_OTHER_OPTION_ID)) {
    return opts;
  }
  return [...opts, { option_id: MCQ_OTHER_OPTION_ID, label: otherLabel }];
}
